app_core_bundle:
    resource: "@AppCoreBundle/Resources/config/routing.yml"
    prefix: /

app_shop_bundle:
    resource: "@AppShopBundle/Resources/config/routing.yml"
    prefix: /

app_admin_bundle:
    resource: "@AppAdminBundle/Resources/config/routing.yml"
    prefix: /admin

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

login_check:
    path: /login_check

logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"