services:

    app_core_bundle.menu_builder:
        class: App\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: [ "@knp_menu.factory" ]

    app_core_bundle.menu.breadcrumb_cart:
        class: Knp\Menu\MenuItem
        factory: [ "@app_core_bundle.menu_builder", createBreadcrumbCartMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: breadcrumbCart }

    app_core_bundle.helper.file_upload:
        class: App\Bundle\CoreBundle\Utils\FileHelper
        arguments: [ '%upload_dir%' ]

    app_core_bundle.manager.file:
        class: App\Bundle\CoreBundle\Utils\FileManager
        arguments:
            - '@app_core_bundle.helper.file_upload'
            - '@doctrine.orm.default_entity_manager'

    app_core_bundle.twig_extension.get_product_extension:
        class: App\Bundle\CoreBundle\Twig\GetProductExtension
        public: false
        arguments: [ '@doctrine.orm.default_entity_manager' ]
        tags:
            - { name: twig.extension }

    app_core_bundle.mail_handler.callback:
        class: App\Bundle\CoreBundle\MailHandler\CallbackMailHandler
        arguments: [ '%general_email%' ]
        calls:
            - [ setTemplatingEngine, [ '@templating' ] ]
        tags:
            - { name: 'visual_craft_mailer.mail_handler', alias: 'callback' }

    app_core_bundle.mail_handler.change_status_order:
        class: App\Bundle\CoreBundle\MailHandler\ChangeStatusOrderHandler
        arguments: [ '%general_email%' ]
        calls:
            - [ setTemplatingEngine, [ '@templating' ] ]
        tags:
            - { name: 'visual_craft_mailer.mail_handler', alias: 'change_status_order' }

    app_core_bundle.twig_extension.get_image_extension:
        class: App\Bundle\CoreBundle\Twig\GetImageExtension
        public: false
        arguments: [ '%base_web_dir%' ]
        tags:
            - { name: twig.extension }

    app_core_bundle.twig_extension.seo_extension:
        class: App\Bundle\CoreBundle\Twig\Extension\SEOExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    app_core_bundle.seo.seo_data_provider:
        class: App\Bundle\CoreBundle\SEO\SEODataProvider

    app_core_bundle.event_listener.product:
        class: App\Bundle\CoreBundle\EventListener\ProductListener
        tags:
            - { name: doctrine.event_listener, event: postUpdate }

    app_core_bundle.event_listener.change_amount:
        class: App\Bundle\CoreBundle\EventListener\ItemOrderListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

