services:

    app_shop_bundle.cart:
        class: App\Bundle\ShopBundle\Service\Cart
        arguments: [ "@request_stack", "@doctrine.orm.default_entity_manager" ]

    app_shop_bundle.multi_currency:
        class: App\Bundle\ShopBundle\Service\MultiCurrency
        arguments: [ "@doctrine.orm.default_entity_manager" ]

    app_shop_bundle.twig.extension.product_extension:
        class: App\Bundle\ShopBundle\Twig\Extension\ProductExtension
        public: false
        tags:
            - { name: twig.extension }

    app_shop_bundle.form.product_count_dto:
        class: App\Bundle\ShopBundle\Form\ProductCountDTOType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
